services:
  jxwaf_base:
    image: "ccr.ccs.tencentyun.com/jxwaf/jxwaf_node:v1.3"
    network_mode: host
    privileged: true
    ulimits:
      nofile:
        soft: 602400
        hard: 602400
    environment:
      HTTP_PORT: 80
      HTTPS_PORT: 443
      JXWAF_SERVER: 
      WAF_AUTH: 
      TZ: Asia/Shanghai
    restart: unless-stopped
    volumes:
      - /opt/jxwaf_data/nginx_cache:/opt/jxwaf_data/nginx_cache
