services:
  jxwaf_base_server:
    image: ccr.ccs.tencentyun.com/jxwaf/jxwaf-mini-server:v4.5
    environment:
      DATABASE_NAME: jxwaf_server
      DATABASE_USER: root
      DATABASE_PASSWORD: jxwaf_rootpassword
      DATABASE_HOST: mysql_db
      DATABASE_PORT: 3306
      CUSTOM_MYSQL_DB: "true"
    ports:
      - "8000:8000"
    depends_on:
      - mysql_db

  mysql_db:
    image: ccr.ccs.tencentyun.com/jxwaf/mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: jxwaf_rootpassword
      MYSQL_DATABASE: jxwaf_server
    ports:
      - "3306:3306"
    volumes:
      - /opt/jxwaf_data/mysql:/var/lib/mysql
