services:
  jxwaf_base_server:
    image: ccr.ccs.tencentyun.com/jxwaf/jxwaf-mini-server:v4.8
    environment:
      DATABASE_NAME: jxwaf_server
      DATABASE_USER: root
      DATABASE_PASSWORD: jxwaf_rootpassword
      DATABASE_HOST: mysql_db
      DATABASE_PORT: 3306
      CUSTOM_MYSQL_DB: "false"
    ports:
      - "8000:8000"
    depends_on:
      - mysql_db

  mysql_db:
    image: ccr.ccs.tencentyun.com/jxwaf/mysql:5.7
    command: 
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: jxwaf_rootpassword
      MYSQL_DATABASE: jxwaf_server
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION: utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    volumes:
      - /opt/jxwaf_data/mysql:/var/lib/mysql
